name: CI for abc-ext

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          sudo apt-get install apt-get install libboost-all-dev -y
          git clone https://github.com/berkeley-abc/abc.git
          ln -s $PWD abc/src/
          cd abc && make -j8
      - name: Test with sample scripts
        if: ${{ success() }}
        run: |
          cd abc && ./abc -F src/ext-folding/example/scripts/run_time_fold.txt
          cd abc && ./abc -F src/ext-folding/example/scripts/run_func_fold.txt
          cd abc && ./abc -F src/ext-folding/example/scripts/run_stru_fold.txt